# Generated by Django 4.0.3 on 2022-03-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateNotes',
            fields=[
                ('short_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('note_crypted', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_password', models.BooleanField(default=False)),
            ],
        ),
    ]
