# Generated by Django 4.0.3 on 2022-03-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatenotes',
            old_name='note_crypted',
            new_name='encrypted_data',
        ),
    ]
