# Generated by Django 4.0.3 on 2022-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiocomposition',
            old_name='number_of_correct_attempts',
            new_name='click_wav',
        ),
        migrations.RemoveField(
            model_name='audiocomposition',
            name='number_of_attempts',
        ),
        migrations.AddField(
            model_name='audiocomposition',
            name='clicks_on_128',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiocomposition',
            name='clicks_on_320',
            field=models.IntegerField(default=0),
        ),
    ]
