# Generated by Django 4.0.3 on 2022-06-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_test', '0002_rename_number_of_correct_attempts_audiocomposition_click_wav_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.AlterModelOptions(
            name='audiocomposition',
            options={'verbose_name': 'Аудио трек', 'verbose_name_plural': 'Аудио треки'},
        ),
    ]
