# Generated by Django 4.0.3 on 2022-06-02 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio_test', '0003_delete_statistic_alter_audiocomposition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocomposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
