# Generated by Django 4.0.3 on 2022-06-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_test', '0004_audiocomposition_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocomposition',
            name='mp3_lowest_quality',
            field=models.IntegerField(choices=[(32, '32k'), (64, '64k'), (96, '96k'), (128, '128k')], default=128, verbose_name='Наихудшее качество'),
        ),
    ]
