# Generated by Django 4.0.3 on 2022-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerFields',
            fields=[
                ('full_url', models.URLField()),
                ('short_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
